### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by kingwiemann** [dsoprea/TabManiac#5]
It appears that Tab Maniac has stopped working on both my Windows 7 machines.  It happened shortly (days/weeks, not hours) after using it once to recover a previous session.  Now, no sessions are listed and it doesn't matter what the update interval is - no new sessions ever appear and all previous sessions are lost.

**Comment by dsoprea** [comment]
What Chrome version are you at? Can you tell if your other extensions seem to still manage their data correctly? Do me a favor and see if any messages show up in the console. If you need help getting there, just ask.

**Comment by kingwiemann** [comment]
I'm on Version 24.0.1312.57 m on my current laptop (the other one is at home).  This is what the console says when I open up the options page from the extensions page:

Uncaught Error: NotFoundError: DOM IDBDatabase Exception 8 extension.js:256
Uncaught Error: NotFoundError: DOM IDBDatabase Exception 8 

When I change the frequency from default 6 to 4, I get the following error message:
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 options.html:37

I am on my company laptop at the moment - it is possible, I suppose, that they've made some change to security policy recently and didn't make it public that could be affecting the "Content Security Policy directive ...".  I can't access my home laptop at the moment - but that isn't subject to company security policy changes and it isn't working, either.

**Comment by dsoprea** [comment]
Thanks. This is helpful/insightful. See if your home laptop emits any
errors, and give me that version, as well.

Dustin

**Comment by kingwiemann** [comment]
That will have to wait until this evening, at the earliest - perhaps as late as Sunday afternoon / evening.

**Comment by dsoprea** [comment]
Do what you can.

Dustin

**Comment by kingwiemann** [comment]
This is what the console says on my home laptop after trying to update the interval:

Uncaught Error: NotFoundError: DOM IDBDatabase Exception 8 extension.js:256
Uncaught Error: NotFoundError: DOM IDBDatabase Exception 8 db.js:210
2
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 options.html:37

**Comment by dsoprea** [comment]
Thank you. I should be able to look at this in a couple of days.

Dustin

**Comment by dsoprea** [comment]
Is there any chance that you could install a version of Chrome that is a couple of months old, to see if it is, in fact, a browser change?

**Comment by kingwiemann** [comment]
Sure - tell me how to get an older version of Chrome.

**Comment by dsoprea** [comment]
Choose your OS from the left:

http://www.oldapps.com/google_chrome.php

Dustin

**Comment by kingwiemann** [comment]
None of the old versions will install on top of my current version.  I suppose that means I have to uninstall my current version first?  (I feel ignorant in asking this question because the answer is probably "duh!")

**Comment by kingwiemann** [comment]
Uninstalled newer version and installed 24.0.1312.32.  Got the following error on the console:

Uncaught Error: NotFoundError: DOM IDBDatabase Exception 8 extension.js:256
Uncaught Error: NotFoundError: DOM IDBDatabase Exception 8 db.js:210
6
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 options.html:37

**Comment by dsoprea** [comment]
This was an involved fix. The updates have been committed and published as version 0.9.9.

**Comment by kingwiemann** [comment]
Thank you - I will give it a try.

**Comment by kingwiemann** [comment]
Thanks - works just fine for me.
