### ISSUE TITLE
Tab_Maniac does not restore

### ISSUE THREAD

**Issue by adgcs** [dsoprea/TabManiac#6]
I've had Tab-Maniac running in Chrome (Version 28.0.1500.72 m) for some time and not had to use it before now.  I had to forcibly restart my pc after it locked up and on restart had lost all my Chrome tabs.  I thought Tab-Maniac would restore them but cannot see how to do this.  What is the process of restoring my tabs please?  Presumably there must be a Tab-Maniac history somewhere on my PC that I can use?

Hope you can advise.

Thanks.

**Comment by dsoprea** [comment]
You should just be able to click on the entry and restore.

I'll have to look at it, tonight.

If you need to know the URLs in the mean time, download the SQLite
command-line client and try inspecting the SQLite database associated with
the extension.

On my current system, the databases are in:

<user path>\AppData\Local\Google\Chrome\User Data\Default\Local Storage

The database should be:

chrome-extension_cdebopdihhnagahmhlhelpdmchpkfbhb_0.localstorage

Dustin

**Comment by adgcs** [comment]
Hi Dustin,

When you say I should be able to click on the entry and restore, where would I find the ‘entry’?

Adrian.

**Comment by dsoprea** [comment]
That's the problem. There should be a list.

Dustin

**Comment by adgcs** [comment]
Where would the list normally reside Dustin?

**Comment by dsoprea** [comment]
Between the top and the bottom, Adrian.

[image: Inline image 1]

Dustin

**Comment by dsoprea** [comment]
The issue has been fixed, pushed, and deployed. You should see the update in version 0.9.9 .

**Comment by dsoprea** [comment]
Remember, do a check to make sure that one or more items are added to the list of saved states. Check the image on the extension's page in the Store.
